


version: '2'
services:
  mariadb:
    # image: docker.io/bitnami/mariadb:10.6
    image: maliksblr92/mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/bitnami/mariadb
    #   - ./bitnami_moodle.sql:/docker-entrypoint-initdb.d/moodle.sql
    networks:
      - moodle_network

  moodle:
    image: docker.io/bitnami/moodle:3
    # image: maliksblr92/moodle:latest
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=user
      - MOODLE_PASSWORD=bitnami
      - MOODLE_EMAIL=maliksblr92@gmail.com
      - MOODLE_SITE_NAME=Evergreen
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb
    networks:
      - moodle_network

volumes:
  mariadb_data:
#     driver: local
#   moodle_data:
#     driver: local
#   moodledata_data:
#     driver: local

networks:
  moodle_network:
    driver: bridge



